### ISSUE TITLE
Allow multiple health checks per API

### ISSUE THREAD

**Issue by amcirillo** [pantsel/konga#111]
Right now Konga has the ability to run a health check on a single endpoint for an API. It would be very useful if we could run health checks against multiple endpoints per API.

Thanks

**Comment by jeremyjpj0916** [comment]
With a point being to test every node your api is hosted on? I suppose if you use the targets functionality kong has then yeah could round robin the health check to all calls and if one fails alert on it, that would be pretty easy 1. check if targets of this endpoint exists. 2. If not just call url by itself, otherwise loop and invoke against all endpoints targets lists and alert on each.
