### ISSUE TITLE
Upstream Targets

### ISSUE THREAD

**Issue by mynameisgv** [pantsel/konga#116]
Hello, 

I have tried many versions of kong with Konga for implementing upstreams.
However i am not able to list/add the targets that are configured. I get Method not allowed error.
I am currently using kong 0.11.0 aws image (also tried docker kong image). 
I was reading thru the issues reported and saw issue 81 with similar issue and was closed pointing to a kong issue.  When i use the kong rest api to add/update upstream/list they work fine. However they don't show up in konga.
When  i use the kong dashboard (another tool for kong administration), i do not see this issue. 
That lists the targets and weights properly. 
Is this something konga can address.

Thanks

**Comment by mynameisgv** [comment]
I was able understand this issue from kong (issue 110 and https://github.com/Kong/kong/issues/2840) and the workaround.
I will wait for the next kong release.

Thanks

**Comment by pantsel** [comment]
@mynameisgv , the only reason i haven't fixed it yet it is because its a Kong regression that they fixed but not yet published an official release with that fix.

Konga's proxy routes to Kong Admin Api are not hardcoded but dynamically generated. 

So in that case is not simply an issue of just adding a `/` in one route. I would have to do some monkey patching explicitly for the `target` routes, publish a version and the undo that again when the version of Kong fixing that issu gets published.

That's why I decided to leave it as it is for now in hopes that they're going to publish a version soon.

If the de

**Comment by mynameisgv** [comment]
@pantsel Thank for the update. 
I did understand the issue. I will wait for the kong release with the permanent fix  instead of applying some hacks.


Thanks
