### ISSUE TITLE
Release Konga as a Docker image

### ISSUE THREAD

**Issue by bakstad** [pantsel/konga#14]
It would be awesome if Konga were distributed as a Docker image with the possibility to configure via environment variables.

This way it would be easy to deploy on clusters and start locally to configure Kong.

**Comment by machbio** [comment]
@pantsel could you explain, your database configuration in Konga - I am not experienced in Sails.. it will really help me to create the docker-image or even docker-compose file by being able to create a stateless dockerfile..

**Comment by pantsel** [comment]
@machbio 

Konga uses local filesystem for storage,  so no actual DB is present on default configuration.

You can use whatever db suits your needs,  via adapters.

http://sailsjs.com/documentation/reference/configuration/sails-config-connections

@bakstad has implemented Docker configuration on this Fork:

https://github.com/bakstad/konga/tree/get_running_on_marathon.

I'll try his implementation and ask for a pull request.

**Comment by bakstad** [comment]
Hi, thanks for answering.

@pantsel Just so you know, I have no experience with any of the frontend technologies in this project. So please take away the ideas from my fork, not necessarily the implementation.

@machbio For me I would be OK with only using the built in local filesystem database as we don't really care that much about permanent users etc. We only use Konga as a tool to configure Kong. But it should be possible to configure the database URLs etc from environment variables.


What I wanted to do:

1. Everything that can be configured should be configurable from environment variables.
2. In order to do this the project has to be built on startup of the container as environment variables are not run time constants, but inserted into static files
3. We use path variables to proxy requests from our load balancer to an actual instance. This caused a problem as Konga works fine on `webpage.com/`, but not on `webpage.com/some-path-prefix/` as it assumed assets are placed on the webroot.

I introduced the environment variables `KONGA_BACKEND_URL` and `KONGA_ROUTE_PREFIX` and there should probably be more. One example would be a way configure databases with host, db name, username, password etc.

**Comment by machbio** [comment]
@pantsel thank you for the amazing application - i wanted a persistent database and hence was trying to understand - how konga works - would love to improve and maybe add direct LDAP integration; as I am trying to demo it for my team..

@bakstad Thank you for the work - I will update you on my progress.. it would be better to create a pull request to this - so we can work unison..

**Comment by bakstad** [comment]
@machbio If you create a PR I will gladly look at it. Just take what you want from my [get_running_on_marathon](https://github.com/bakstad/konga/tree/get_running_on_marathon) branch if it's usable.

**Comment by pantsel** [comment]
@machbio, 
@bakstad 

Check out the [dev](https://github.com/pantsel/konga/tree/dev)  branch.

I have addressed some of the issues mentioned here.

Feel free to drop some feedback or PRs so we can merge it to master when ready.

**Comment by bakstad** [comment]
@pantsel Great work!

One thing I noticed are the variables `KONGA_FRONTEND_PORT` and `KONGA_BACKEND_PORT'. They probably don't make much sense in a docker/container context. The application inside the container should listen to fixed ports as these are exposed by Docker based on the Dockerfile. Outside the docker context they might be useful for someone though.

Have you set up a docker hub account yet? It is really easy to set up automatic build so the images will always be in sync and it's also possible to release images based on branches. For instance I would love to test the dev version out.

**Comment by pantsel** [comment]
Yup, I will make that later tonight.

You're also right about the ports but it still can be tested as they're optional. 

I will remove them on a future commit.

**Comment by pantsel** [comment]
@bakstad 

Konga is on docker hub.

<code>docker pull pantsel/konga</code>

<code>KONGA_BACKEND_URL</code> must be set

**Comment by bakstad** [comment]
@pantsel Nice! It would be nice if you also set up branches (dev) to be automatically built as well.

I'm going away for a week so I won't be able to test it until I'm back home.

**Comment by lostphilosopher** [comment]
Hey folks, I've got Kong running on Docker, and wanted to *Docker-all-the-things* and get Kong GUI running on Docker too. I realize this is experimental. Here's what I'm experiencing: 

**Start a Postgres database for Kong:**
`docker run -d --name kong-database -p 5433:5433 -e "POSTGRES_USER=kong" -e "POSTGRES_DB=kong" postgres:9.4`

**Start Kong:**
`docker run -d --name kong --link kong-database:kong-database -e "KONG_DATABASE=postgres" -e "KONG_POSTGRES_CONTACT_POINTS=kong-database" -e "KONG_PG_HOST=kong-database" -p 8000:8000 -p 8443:8443 -p 8001:8001 -p 7946:7946 -p 7946:7946/udp kong`

*At this point I can verify that calls to localhost:8000 and localhost:8001 work as expected.*

**Start Konga (Kong GUI):**
`docker run -d --name kong-gui -p 8000:3000 -p 8001:1338 -e KONGA_BACKEND_URL=http://127.0.0.1:8001 pantsel/konga` 
(Per: https://github.com/pantsel/konga/tree/dev#running-konga) 

**Error:** 
`docker: Error response from daemon: driver failed programming external connectivity on endpoint kong-gui (58e00ec5e91da90a2f88fba1472104d42c0389dec909c9eb84ae0d002308c1aa): Bind for 0.0.0.0:8000 failed: port is already allocated.`

My docker-fu is weak, so that's surely part of the problem, but I could use some help and some documentation around using Konga with a Docker instance of Kong. It seems I need to tell Konga where it can reach Kong without re-allocating the port?

Let me know if there's information I can provide that would be helpful.

**Comment by ammmze** [comment]
@lostphilosopher thats because you are trying to forward port 8000 to konga AND kong. So you'd probably want something like this (*assuming `KONGA_BACKEND_URL` is intended to be the kong admin url)

```
docker run -d --name kong-gui -p 3000:3000 -p 1338:1338 -e KONGA_BACKEND_URL=http://kong:8001 --link kong:kong pantsel/konga
```

* I don't know if that is what is intended for the `KONGA_BACKEND_URL`. I've not tried Konga yet ... was waiting for the docker stuff before I jumped in. If `KONGA_BACKEND_URL` is intended to be the url to the kong admin api, i would recommend that env var gets changed to `KONG_ADMIN_URL`.

**Comment by pantsel** [comment]
Hello @lostphilosopher,

There are a couple of things that needs to be changed in the way you are trying to run Konga.

First of all, the ports you are exposing for Konga, are actually Kong's ports.

Kong itself is exposing port 8000 (gateway) and 8001 (admin API) so for starters those 2 ports are preoccupied by Kong.

So, <code>-p 8000:3000</code> which refers to the ports Kongas frontend is exposed, needs to be changed to <code>-p {any other port than 8001 or 8000}:3000</code>

and

 <code>-p 8001:1338</code>which refers to the port Kongas backend is exposed, needs to be changed to <code>-p {any other port than 8001 or 8000}:3000</code>.

Secondly ,<code>KONGA_BACKEND_URL</code> environment variable is the URL  to Kongas backend, not Kong's. 

It needs to be accessible from the GUI running on the browser. So instead of <code>127.0.0.1</code>, the IP  should be the IP of the server Konga is running on and instead of <code>:8001</code> the port should be the port Kongas backend is exposed (previous step).

Finally, the part of Konga that's actually communicating with Kong's admin API is the backend.
In order for Konga to be able to see Kong's container you will need to add a link : <code>--link kong:kong</code> and the node you will need to setup in the GUI, will be <code>http://kong:8001</code>.

To wrap things up.

Your run command should be as follows :
<code>docker run -d --name kong-gui -p {free port for frontend}:3000 -p {free port for frontend}:1338 -e KONGA_BACKEND_URL=http://{your servers ip}:{the previous free port for backend} --link kong:kong pantsel/konga</code>

Hope this wasn't too confusing.... :)

**Comment by pantsel** [comment]
*** Note ***

If you try to build Konga from the dev branch of this project, you will need to <code>cd frontend && gulp dist</code> first.

Alternatively, you can get it from dockerhub

<pre>
$ docker pull pantsel/konga
$ docker run -d --name konga -p 3000:3000 -p 1338:1338 -e KONGA_BACKEND_URL=http://{your server's public ip}:1338 --link kong:kong pantsel/konga
</pre>

The GUI will be available at <code>http://{your server's public ip}:3000</code>

Login and go to settings -> new node and add <code>http://kong:8001</code> for Kong Admin URL.

**Comment by lostphilosopher** [comment]
@pantsel Thank you very much for the help! I'm going to work on on this a bit and then I'll report back. I've learned a lot already. Thanks again.

**Comment by pantsel** [comment]
@lostphilosopher 

Great! Glad you got it running.
I know its a bit confusing right now, but the overall integration and documentation will be updated as we go. So, any feedback is welcome.

Cheers!

**Comment by pantsel** [comment]
Closing this issue. Feature integrated on commit https://github.com/pantsel/konga/commit/58412c68b2ffff9eef7706ace46fc1587b963896 .
