### ISSUE TITLE
Fetch size on ListConfigService is too big

### ISSUE THREAD

**Issue by andreaugusto** [pantsel/konga#140]
Hi, guys!

I'm using Konga as an admin for Kong and, before anything else, gratz for the great work!

I've ran into this issue after upgrading from Cassandra 2 to Cassandra 3. Whenever I try to open the APIs, Certificates or Upstreams, I get this error saying that there was a problem fetching the resource. Taking a look at what kind of request Konga is doing, I found out that it was trying to fetch for the APIs and setting a limit to 4294967295. Here is the error I get from Kong:

```
[error] 80#0: *1823 [lua] responses.lua:107: handler(): [Protocol error] Invalid page size: A page size should be strictly positive, got -1, client: 127.0.0.1, server: kong_admin, request: "GET /apis?size=4294967295 HTTP/1.1", host: "localhost:8001"
```

After successfully reproducing the same behavior via curl (`curl localhost:8001/apis?size=4294967295`) I started experimenting with the numbers to find out what was the highest supported number for me and it is somewhere around 2000000000. That meant this number was the problem.

I've made a change [here](https://github.com/pantsel/konga/blob/930b99d40bcc7b348ffeb69c71eac0ec8e56b297/assets/js/app/core/services/ListConfigService.js#L442) locally to a lower number and after that everything worked well.

I'd like to know:

1. Is this number is mandatory?
2. If it is not could it be set to a lower one?

If you guys agree, I could send you a PR with the needed change and tests.

Then again, thanks!

**Comment by pantsel** [comment]
@andreaugusto, hi.

This is a bit complicated issue that was bound to be raised at some point. 

Here' s what happens.

Konga doesn't rely on Kongs API for listing as it is very limited and in my opinion pretty unusable for a GUI. It doesn't provide meta data for proper pagination, it messes up ordering of fetched items and lacks a proper text search functionallity.

For me, it was mandatoy that Konga could provide an at least basic and nice listin UI.

In order to overcome that obstacle, I had 2 options.

Either query the db directly, or fetch everything in memory and from there handle it the way I see fit.

Since I didn't want Konga to be dependant on Kong's db, I went with the later. I make a GET request with a very large limit of ``4294967295``, load everything in the browser's memory, and handle it from there.

To be frank I've never tested having millions of records but it works pretty fast for up to 20.000 items and the loading time is acceptable.

Now, to answer your question. If you have for example more than <code>2000000000</code> consumers and set the fetch limit to <code>2000000000</code>, that will be all the consumers you will be able to manage and that's it. 

If you have less than <code>2000000000</code> and your issue is just the number, then yes, you can set the fetch limit to that with no probs.

**Comment by jeremyjpj0916** [comment]
I think Kong version also becomes relevant in this issue. I run Kong 11.1 + Cassandra 3.x and am not receiving such error messages on Konga's query size.

**Comment by andreaugusto** [comment]
Thanks for the answers! I did configure the itemsFetchSize and it is working right now.
