### ISSUE TITLE
Konga dashboard will not load if konga installed on seperate machine other than kong machine

### ISSUE THREAD

**Issue by jayeshkulkarni** [pantsel/konga#167]
Konga dashboard will not load if konga installed on separate machine other than kong machine... if i install it on same kong api machine it works fine. I am getting below error 

debug: KongProxyController:req.url /status
error: KongProxyController request error { message: 'Not found' }
debug: KongProxyController:req.url /status
debug: KongProxyController:req.url
error: KongProxyController request error { message: 'Not found' }

Am i missing any configuration ?

**Comment by balexandre** [comment]
I noticed that you can't end the kong api url with an ending `/` for example `http://konga.herokuapps.com/kong-api` instead of `http://konga.herokuapps.com/kong-api/` - can you re-check if this is the issue...

If not, you can always add `console.log` statements to the `KongProxyController.js` in the `Proxy` method, for example:

```javascript
sails.log.debug("KongProxyController:req.url 1", KongService.headers(req.connection, true))
sails.log.debug("KongProxyController:req.url 2", req.connection.kong_admin_url + req.url)
```

so you know the exact host and url call being made

**Comment by pantsel** [comment]
@jayeshkulkarni ,
any update on this?

Everything seems to work fine here.

**Comment by jayeshkulkarni** [comment]
Works fine now

On 03-Mar-2018 3:09 AM, "Panagis Tselentis" <notifications@github.com>
wrote:

@jayeshkulkarni <https://github.com/jayeshkulkarni> ,
any update on this?

Everything seems to work fine here.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/pantsel/konga/issues/167#issuecomment-370060175>, or mute
the thread
