### ISSUE TITLE
Konga plugin config removes newline from config values

### ISSUE THREAD

**Issue by florian-besser** [pantsel/konga#189]
This is in regard to the following comment:

https://github.com/pantsel/konga/pull/17#issuecomment-330850680

We try to configure a custom plugin by adding a public key. But Konga will strip away any newline characters and replace them with spaces instead, which makes the public key invalid.

Version used: `latest` Docker tag for `pantsel/konga`
kong version: 0.12.2

Calling kong directly works. When tracing the AJAX call in Browser tools we can see the newlines being stripped away by Konga before sending the plugin config to the server.

**Comment by pantsel** [comment]
What is the plugins configuration (as stated in your .lua files)?

This is def an issue with custom plugins and we have to discuss ion ho to solve it. 

Here's what happens.

In order to create the plugin form dynamicaly, I get it's schema from Kongs API 
<code>/plugins/schema/{plugin name}</code>.

The response is something like this
<pre>
{
    "fields": {
        "hide_credentials": {
            "default": false,
            "type": "boolean"
        },
        "key_names": {
            "default": "function",
            "required": true,
            "type": "array"
        }
    }
}
</pre>

If a field type is <code>string</code>, I translate it to a text input which by definition cannot accept new lines.

I need a way to know, that the specific input must be a <code>textarea</instead> and frankly, I have no idea if or how this can be done.

One solution would be to translate all <code>string</code> fields to textareas instead of text inputs so it can work with non standard plugins (that i cannot monkey patch).

**Comment by florian-besser** [comment]
This was out schema.lua

```
return {
   no_consumer = true,
   fields = {
    pub_key = { type = "string", default = [[-----BEGIN PUBLIC KEY-----
ADD YOUR KEY!!!
-----END PUBLIC KEY-----]]
     }
   }
 }
```

AFAIK Kong config types only support "string" and have no "textfield" equivalent.

In the end we were able to configure Kong directly using:
```
curl -X POST http://localhost:8001/apis/<ApiName>/plugins -F "name=<pluginName>" -F "config.pub_key=@/home/florian/.ssh/public.pem"
```

I also have no idea how to differentiate whether config "string" should accept newlines or not. But since Kong accepts newlines for "string" my first suggestion would be to use HTML "textfield"s for every "string" config value. Then at least the GUI is consistent with the raw API.

**Comment by pantsel** [comment]
@florian-besser ,

pull thel atest commit from master and check out if things work as expected

**Comment by florian-besser** [comment]
Verified working @pantsel . Thanks a lot for the speedy fix.

For others: I did have to clear my browser cache to see the changes, as Konga was still cached!
