### ISSUE TITLE
frontend model npm install error

### ISSUE THREAD

**Issue by FRANDAVID** [pantsel/konga#2]
hi,@pantsel i have download konga-0.2.1 and follow the install step ,when i installed all dependencies and run npm install in ~/konga-0.2.1 i got some errors:

npm install

> kongadmin@0.2.1 install /Users/{user}/tmp/konga-0.2.1
> cd frontend && npm install && cd ../backend && npm install

> frontend@0.1.1 postinstall /Users/{user}/tmp/konga-0.2.1/frontend
> bower install

module.js:474
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:17:20
    at Object.<anonymous> (/Users/{user}/tmp/konga-0.2.1/frontend/node_modules/bower/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.1.0
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE
npm ERR! frontend@0.1.1 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frontend@0.1.1 postinstall script 'bower install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the frontend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs frontend
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls frontend
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/{user}/tmp/konga-0.2.1/frontend/npm-debug.log

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.1.0
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE
npm ERR! kongadmin@0.2.1 install: `cd frontend && npm install && cd ../backend && npm install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kongadmin@0.2.1 install script 'cd frontend && npm install && cd ../backend && npm install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the kongadmin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd frontend && npm install && cd ../backend && npm install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs kongadmin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls kongadmin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/{user}/tmp/konga-0.2.1/npm-debug.log

my environment is 
node -v
v7.1.0
npm -v
4.0.2

**Comment by pantsel** [comment]
Hey, @FRANDAVID .
This seems to me more of a nodejs installlation problem [https://github.com/nodejs/node/issues/9377](https://github.com/nodejs/node/issues/9377).

Have you tried installing Konga with node js version other that v7.1.0?

**Comment by FRANDAVID** [comment]
hi, @pantsel thanks you reply, i have change the package.json update bower version ->1.8.0 so the error gone and frotend model running,with some warnings, look like:
rc/app/core/models/DataModel.js
  line 366  col 41  Missing semicolon.

  ⚠  1 warning


src/app/core/plugins/angular-matchheight.js
  line 11  col 13  Missing "use strict" statement.
  line 21  col 35  Expected '===' and instead saw '=='.
  line 27  col 25  'i' is already defined.
  line 38  col 46  'attrs' is defined but never used.

  ✖  1 error
  ⚠  3 warnings


src/app/core/plugins/material.spinner.js
  line 2   col 5     Missing "use strict" statement.
  line 13  col 5     Missing "use strict" statement.
  line 13  col 92    Strings must use singlequote.
  line 13  col 82    Expected '===' and instead saw '=='.
  line 13  col 111   Expected '{' and instead saw 'return'.
  line 13  col 131   Expected '{' and instead saw 'return'.
  line 13  col 184   Strings must use singlequote.
  line 13  col 190   Strings must use singlequote.
  line 13  col 204   Missing semicolon.
  line 13  col 223   Strings must use singlequote.
  line 13  col 204   Expected an identifier and instead saw '='.
  line 13  col 204   Expected an assignment or function call and instead saw an expression.
  line 13  col 205   Missing semicolon.
  line 13  col 224   Expected an assignment or function call and instead saw an expression.
  line 13  col 225   Missing semicolon.
  line 13  col 317   Missing semicolon.
  line 13  col 339   Missing semicolon.
  line 13  col 359   Missing semicolon.
  line 13  col 392   Strings must use singlequote.
  line 13  col 382   Expected '===' and instead saw '=='.
  line 13  col 429   Expected '{' and instead saw 's'.
  line 13  col 445   Missing semicolon.
  line 19  col 91    Missing semicolon.
  line 19  col 120   Expected '{' and instead saw 'return'.
  line 19  col 194   Strings must use singlequote.
  line 19  col 226   Strings must use singlequote.
  line 19  col 228   Expected '{' and instead saw 'return'.
  line 19  col 234   Missing semicolon.
  line 19  col 250   Missing semicolon.
  line 19  col 291   Strings must use singlequote.
  line 19  col 317   Strings must use singlequote.
  line 19  col 350   Strings must use singlequote.
  line 19  col 397   Strings must use singlequote.
  line 19  col 451   Missing '()' invoking a constructor.
  line 19  col 520   Expected an assignment or function call and instead saw an expression.
  line 19  col 521   Missing semicolon.
  line 19  col 853   Missing semicolon.
  line 19  col 907   Strings must use singlequote.
  line 19  col 960   Strings must use singlequote.
  line 19  col 921   Missing 'new' prefix when invoking a constructor.
  line 19  col 967   Strings must use singlequote.
  line 19  col 973   Strings must use singlequote.
  line 19  col 974   Missing semicolon.
  line 19  col 1011  Strings must use singlequote.
  line 19  col 1093  Strings must use singlequote.
  line 19  col 1115  Strings must use singlequote.
  line 19  col 1170  Missing semicolon.
  line 19  col 1189  Strings must use singlequote.
  line 19  col 1205  Missing semicolon.
  line 19  col 1252  Strings must use singlequote.
  line 19  col 1252  Too many errors. (11% scanned).

  ✖  6 errors
  ⚠  45 warnings


src/app/core/plugins/uiBreadcrumbs.js
  line 15  col 5  Missing "use strict" statement.

  ✖  1 error  ⚠  0 warning


src/app/core/services/DialogService.js
  line 43  col 54  Missing semicolon.
  line 44  col 18  Missing semicolon.
  line 46  col 55  Missing semicolon.
  line 47  col 18  Missing semicolon.
  line 52  col 47  'd' is defined but never used.
  line 56  col 28  Strings must use singlequote.
  line 57  col 25  Missing semicolon.
  line 59  col 29  Strings must use singlequote.
  line 60  col 26  Missing semicolon.
  line 20  col 35  '_' is defined but never used.

  ⚠  10 warnings

now i'm installing the backend model .i don't know whether is right way to solve the problem.

**Comment by FRANDAVID** [comment]
i have another question that ,can i run frotend model without backend model?

**Comment by pantsel** [comment]
@FRANDAVID 
I will update bowers' version and rerun tests.

The warnings are due to the linter running on dev mode. Don't be alarmed by them. Imin the process of refactoring.

Unfortunatelly no, the backend is required to be lifted because it handles the API

**Comment by FRANDAVID** [comment]
@pantsel thanks   i am new to node.js and kong ,now i'm installing the backend model .i don't know whether change the bower version is right way to solve the problem. sorry for my poor English! :)

**Comment by pantsel** [comment]
The issue is confirmed to occur with node.js v0.7.10 and bower v1.6.5

<pre>
> kongadmin@0.2.3 install /home/travis/build/pantsel/konga
> cd frontend && npm install && cd ../backend && npm install
> frontend@0.1.1 postinstall /home/travis/build/pantsel/konga/frontend
> bower install
module.js:474
    throw err;
    ^
Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:17:20
    at Object.<anonymous> (/home/travis/build/pantsel/konga/frontend/node_modules/bower/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v7.1.0/bin/node" "/home/travis/.nvm/versions/node/v7.1.0/bin/npm" "install"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! frontend@0.1.1 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontend@0.1.1 postinstall script 'bower install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR!0m If you do, this is most likely a problem with the frontend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs frontend
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls frontend
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/pantsel/konga/frontend/npm-debug.log
npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v7.1.0/bin/node" "/home/travis/.nvm/versions/node/v7.1.0/bin/npm" "install"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! kongadmin@0.2.3 install: `cd frontend && npm install && cd ../backend && npm install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kongadmin@0.2.3 install script 'cd frontend && npm install && cd ../backend && npm install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the kongadmin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd frontend && npm install && cd ../backend && npm install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs kongadmin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls kongadmin
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/pantsel/konga/npm-debug.log
The command "eval npm install " failed 3 times.
The command "npm install " failed and exited with 1 during .
Your build has been stopped.
</pre>

Updated bower version to ^1.8.0  and the problem seems to be resolved.  

Also added node.js LTS and Current versions (v7.1.10) to travis.yml file.

Thanks for the feedback @FRANDAVID  :)
