### ISSUE TITLE
demo is broken

### ISSUE THREAD

**Issue by borestad** [pantsel/konga#205]
Hi! Nice project, but you seriously need to have some QA before deploying.

First login (Chrome)
![image](https://user-images.githubusercontent.com/286455/39697426-30a90fa8-51f1-11e8-8b92-fc69d3300085.png)

First login (Firefox)
![image](https://user-images.githubusercontent.com/286455/39697451-4439817e-51f1-11e8-82d7-84682f03fe0e.png)

Maybe some https://github.com/GoogleChrome/puppeteer could be used for autotest that a login is at least working?

**Comment by pantsel** [comment]
The demo instance is not going to be up for much longer because I cannot support it. 

It may be the case that things do not run as expected from time to time up there.

Konga is a free app, doesn't really need a demo instance. Anyone can just download it and test it.

Closing this because the demo instance will not be supported for long.

Cheers.
