### ISSUE TITLE
Is there a way to clear all health checks manually

### ISSUE THREAD

**Issue by cberlandier** [pantsel/konga#211]
We have 2 health checks that we **disabled** - but they both still hit our end-points each minute?

**Comment by pantsel** [comment]
@cberlandier ,
This bug is fixed on the new version of Konga. Right now on the `next` branch but will be commited to muster sometime today or tomorrow. The caveat is that due to the nature of the problem, you will have to remove the previously orphaned health checks manually from Konga's db,

Thanks for the feedback!
