### ISSUE TITLE
Is there a way to custom users privildege hide/show connections or api

### ISSUE THREAD

**Issue by Niradnik** [pantsel/konga#213]
Hello, 

thanks for your job! 
As said in the title I would like to have several user and lets say user A can see and manage api 1 to 5 and user B can see and manage api 4 to 10. 
Is there a way to do so ?

Have a good day,
Thanks again !

**Comment by pantsel** [comment]
@Niradnik , I'm afraid there is no way to do that right.
I'll consider it as a future Enhancement tho.

In the meatime, im closing this since it's not really an issue.

I'm also referring you to the official Konga Lobby on gitter

https://gitter.im/pantsel-konga/Lobby

If you need any help or have any questions, the people and me are really active there.

Cheers
