### ISSUE TITLE
version-0.13.0 need much more memory then 0.10.x

### ISSUE THREAD

**Issue by wen911119** [pantsel/konga#285]
I just updated from 0.10.6, I notice that the new version cost much more memory than before!
0.10.6 ===> 76M
0.13.0 ===> 180M
Do you have any plans to optimize this in the future ?

**Comment by wen911119** [comment]
> @wen911119 , are you running on development mode?

production mode

**Comment by wen911119** [comment]
![20181011155652](https://user-images.githubusercontent.com/13494648/46789524-3344a200-cd6f-11e8-8652-1f2c1eb2a3bf.png)
![20181011155712](https://user-images.githubusercontent.com/13494648/46789560-4fe0da00-cd6f-11e8-9ff1-15b61ce808d7.png)

![20181011155745](https://user-images.githubusercontent.com/13494648/46789530-3770bf80-cd6f-11e8-8d5b-8565475e8725.png)

**Comment by wen911119** [comment]
0.10.6
![20181011161018](https://user-images.githubusercontent.com/13494648/46789922-4f950e80-cd70-11e8-9f56-29b22c95ac43.png)

**Comment by pantsel** [comment]
OK. 
Konga 0.13.0 has a lot of extra stuff bundled in comparison with 0.10. So that is kind of logical. 
It occupies 120M on my server running non stop for more than 3months.
120 - 180M is not too much memory for an app bundled with Konga's features.

That being said, on future releases i'll see if there is something I can do to lower it down, but don't expect much of a difference.
