### ISSUE TITLE
upstream can not be renamed

### ISSUE THREAD

**Issue by tumluliu** [pantsel/konga#34]
to name a upstream on creation is ok. but it can not be renamed anymore. an error was reported as follows:

```
ReferenceError: $uibModalInstance is not defined
    at production.min.js:51
    at processQueue (production.min.js:9)
    at production.min.js:9
    at Scope.$eval (production.min.js:9)
    at Scope.$digest (production.min.js:9)
    at Scope.$apply (production.min.js:9)
    at done (production.min.js:8)
    at completeRequest (production.min.js:8)
    at XMLHttpRequest.xhr.onload (production.min.js:8)
```

**Comment by pantsel** [comment]
Hi @tumluliu ,
after a conversation i had with Kong's developers, you are actually not supposed to be able to update or delete upstreams because you would be messing with the upstream history stack on the server. You can only overwrite an upstream by creating a new one on top of it.

Now, the error you posted is clearly a bug which will be fixed, but, the update and delete functionality will be removed from upstreams in the upcoming version of Konga.

Once again, thanks for the feedback!

**Comment by tumluliu** [comment]
thanks a lot, @pantsel ! That sounds reasonable according to Kong 0.10's documents. For the moment, I will avoid renaming a upstream.
