### ISSUE TITLE
create service route encouter has not pass the params of "paths"

### ISSUE THREAD

**Issue by lookhua** [pantsel/konga#376]
create service route encouter error, the page form do not pass the params of "paths"

**Comment by jsdecena** [comment]
I think this is the same with my issue https://github.com/pantsel/konga/issues/375 The UI might not be passing the correct `Content-Type` because when I use the postman, it goes thru the admin. I just don't have the time to look at the error but maybe tomorrow (sunday -- on my timezone), I may be able to look at it. All create / update methods are not working.

**Comment by lookhua** [comment]
thanks, it is my own problem, when i input the path value ,i do not intput "enter" key. so the page can not get the path value
