### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by flowdopip** [pantsel/konga#42]
Hi,

After setup when start the app the screen is blacks and i have a lot of js errors.

Any ideia?

thanks

**Comment by pantsel** [comment]
Hi @flowdopip , Try clearing your browsers localstorage.
This issue occurs on the latest release?
https://github.com/pantsel/konga/releases/tag/0.6.3

**Comment by flowdopip** [comment]
Any solution for that?

this is the errors
![image](https://cloud.githubusercontent.com/assets/5880313/24807336/b480bc96-1baf-11e7-8f35-5e96d7bf3aea.png)

**Comment by pantsel** [comment]
It seems that you havent installed the dependencies. You need to run npm install and bower install in the project dir

**Comment by Harshil1989** [comment]
Got the same issue..

![capture](https://cloud.githubusercontent.com/assets/24707036/24889300/23b11bdc-1ea4-11e7-88b2-745c527f94f4.PNG)

**Comment by flowdopip** [comment]
I´ve installed bower, but still doesnt work

**Comment by pantsel** [comment]
@flowdopip ,
the errors you posted clearly state that the project is missing dependencies probably because 
<code>bower install</code> needs to run inside the project's dir.

You need to <code>cd</code> into Konga's root directory and type <code>bower install</code>.

Can you please post the output of the <code>bower install</code> command?

If that's not the case, the only thing I can think of, is that the project is taking some time to compile it's assets on the first run and probably if you keep refreshing the page, those errors will disappear after a few seconds.

**Comment by flowdopip** [comment]
Hi, it´s wrong permission on bower install, thanks, its working
