### ISSUE TITLE
Improvement: Display api name instead of id in plugins section

### ISSUE THREAD

**Issue by PauloGDPeixoto** [pantsel/konga#44]
It would be so much easier to identify the api to which the plugin is attributed if the API field contained the api name instead of the id :)

**Comment by pantsel** [comment]
Hi @PauloGDPeixoto ,
indeed, but there is a reason for that.

Konga is not querying Kong's database directly. It just provides an interface to Kong's admin API.

The response api object Kong provides at <code>/plugins</code> endpoint is :
<pre>
{
      "api_id": "285a12ea-0253-4a33-87df-cd883031c72c",
      "id": "bfc9ffba-5dfd-4a40-a50e-ef96959cc912",
      "created_at": 1491268282429,
      "enabled": true,
      "name": "key-auth",
      "config": {
        "hide_credentials": true,
        "key_names": {},
        "anonymous": ""
      }
    },
</pre>

In order to get the actual <code>API</code> object from the <code>api_id</code>, Konga would have to  perform a <code>GET</code> request to <code>/apis/{api_id}</code> for every Plugin on the list.

If many plugins are listed and many users are playing with Konga you end up DOSing Kong a little bit.

So unless Konga is querying the actual database -which it isn't at he moment - this is not a very good practice.

Cheers and thanks so much for the feedback. Your suggestions have been really helpful!

**Comment by PauloGDPeixoto** [comment]
I understand, and in that case, it makes perfect sense not to put more stress on kong. Thank you for being so receptive!

**Comment by davinwang** [comment]
@pantsel Hi, Panagis, I think this reuqest is "doable" now since results are paged by 25 items each. The DOS concern is still valid but I think calling 25 times each time is somewhat acceptable. Thanks.
