### ISSUE TITLE
bootstrap.js error : EACCES: permission denied, mkdir '/kongadata/'

### ISSUE THREAD

**Issue by rjpalermo1** [pantsel/konga#77]
I followed the git clone method install using Docker Kong/Cassandra containers and was getting:

> error: Bootstrap encountered an error: (see below)
> error: Error: EACCES: permission denied, mkdir '/kongadata/'
>     at /Users/Me/Develop/Kong/konga/config/bootstrap.js:19:16

in the bootstrap.js I had to remove the leading `/` from kongadata in the  process.env.STORAGE_PATH
```
    // Create Konga data directories
    var dirs = [( process.env.STORAGE_PATH || 'kongadata/' ), ( process.env.STORAGE_PATH || 'kongadata/' )+ 'uploads']
```

**Comment by pantsel** [comment]
Hi @rjpalermo1 .

Instead of removing the leading '/', you could instead define the env variable <code>STORAGE_PATH</code> as you can see in the code you posted.

That way you won't have any problems syncing with the repository.

The leading '/' is there because the <code>/kongadata</code> directory is used as a docker volume in docker builds which is also the recommended way to run Konga.

The caveat is that it throws the <code>EACCES</code> error when your building from source and Konga has no permissions to the specified directory, but again, all those things are configurable via env vars so no problem there.

This is something I need to document out in README as well so that it becomes more understandable.

Cheers, and thanks for the feedbak!

**Comment by rjpalermo1** [comment]
Got it!  Great stuff.  You have a day job or freelancer?

Closing...

**Comment by pantsel** [comment]
Working as a software engineer in a software house and doing a bit of freelancing as well.
